#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &

picom --daemon
feh --bg-fill "$HOME/.config/bspwm/1920x1080-trolley-grey-solid-color-background.jpg"

killall -q polybar

echo "---" | tee -a /tmp/polybar.log
polybar top 2>&1 | tee -a /tmp/polybar.log & disown

bspc monitor -d  1 2 3 4 5

bspc config border_width         5
bspc config window_gap          12

bspc config focused_border_color "#F38BA8"
bspc config normal_border_color "#585B70"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox-esr desktop='^2' follow=on focus=on
bspc rule -a Emulator state=floating
