#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x dunst >/dev/null || dunst &

wmname LG3D

picom --daemon
feh --bg-fill "$HOME/.config/bspwm/1920x1080-trolley-grey-solid-color-background.jpg"

killall -q polybar
mpris-proxy &

echo "---" | tee -a /tmp/polybar.log
polybar top 2>&1 | tee -a /tmp/polybar.log &
disown

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 5
bspc config window_gap 12

bspc config focused_border_color "#b4befe"
bspc config normal_border_color "#585B70"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Hack for not focusing weird windows
bspc config ignore_ewmh_focus true

bspc rule -a firefox-esr desktop='^2' follow=on focus=on
bspc rule -a Spotify desktop='^4' state=floating follow=off focus=off
bspc rule -a discord desktop='^5' follow=off focus=off
bspc rule -a Emulator state=floating desktop='^4'

# Float
bspc rule -a qBittorrent state=floating
bspc rule -a ghidra-Ghidra state=floating
bspc rule -a Joplin state=floating
bspc rule -a feh state=floating
bspc rule -a Virt-manager state=floating
