[global/wm]

include-file = $HOME/.config/polybar/mocha.ini

[bar/top]
background = ${colors.base}
border-color = ${colors.crust}
border-size = 4pt
font-0 = FiraCode Nerd Font Mono:size=12;2
foreground = ${colors.surface0}
width = 100%
height = 14pt

modules-left = bspwm
modules-center = 
modules-right = wireless-network mpd date


[module/systray]
type = internal/tray

[module/bspwm]

type = internal/bspwm
# pin-workspaces = true
inline-mode = false
enable-click = false
enable-scroll = false
reverse-scroll = false
occupied-scroll = true

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5

label-focused = %icon%
label-focused-background = ${colors.pink}
label-focused-foreground = ${colors.surface0}
label-focused-padding = 2

label-occupied = %icon%
label-occupied-background = ${colors.base}
label-occupied-foreground = ${colors.text}
label-occupied-padding = 2

label-empty = %icon%
label-empty-background = ${colors.base}
label-empty-foreground = ${colors.text}
label-empty-padding = 2

label-urgent = %icon%
label-urgent-background = ${colors.base}
label-urgent-foreground = ${colors.text}
label-urgent-padding = 2

[module/date]
type = internal/date
interval = 1.0
date = %Y-%m-%d%
time = %H:%M

format =  <label>
format-background = ${colors.base}
format-foreground = ${colors.text}

label = %date% %time%
label-font = 3
label-foreground = ${colors.text}

[module/mpd]
type = internal/mpd

host = 127.0.0.1
port = 6600
password = mysecretpassword

interval = 2

format-online = <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat> <icon-random>  <bar-progress> <label-time>  <label-song>
label-song = 𝄞 %artist% - %title%
label-offline = 🎜 mpd is offline

icon-play = ⏵
icon-pause = ⏸
icon-stop = ⏹
icon-prev = ⏮
icon-next = ⏭
icon-seekb = ⏪
icon-seekf = ⏩
icon-random = 🔀
icon-repeat = 🔁
icon-repeatone = 🔂
icon-single = 🔂
icon-consume = ✀

[module/wireless-network]
type = internal/network
interface = wlp7s0

interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-disconnected = <label-disconnected>

label-connected = %essid% %downspeed:9%
label-connected-foreground = #eefafa

label-disconnected = not connected
label-disconnected-foreground = #66ffff

ramp-signal-0 = 😱
ramp-signal-1 = 😠
ramp-signal-2 = 😒
ramp-signal-3 = 😊
ramp-signal-4 = 😃
ramp-signal-5 = 😈
