[global/wm]

include-file = $HOME/.config/polybar/mocha.ini

[bar/top]
background = ${colors.base}
border-color = ${colors.base}
border-size = 4pt
font-0 = FiraCode Nerd Font Mono:size=12;2
font-1 = FiraCode Nerd Font Mono:size=15;2
font-2 = FiraCode Nerd Font Mono:size=13;2
foreground = ${colors.text}
width = 100%
height = 14pt

modules-left = bspwm
modules-center = date
modules-right = now-playing sep cpu memory sep pulseaudio wireless-network bluetooth

wm-restack = bspwm

[module/systray]
type = internal/tray

[module/sep]
type = custom/text

format = <label>
format-background = ${colors.base}
format-foreground = ${colors.text}

label = " | "

[module/title]
type = internal/xwindow

format = <label>
format-background = ${colors.base}
format-foreground = ${colors.text}

label = %title%
label-maxlen = 30

label-empty =
label-empty-foreground = #707880

[module/bspwm]
type = internal/bspwm

pin-workspaces = true
inline-mode = false
enable-click = true
enable-scroll = false
reverse-scroll = false
occupied-scroll = true

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5

#label-focused = 󰄯
label-focused = 󰄯
label-focused-background = ${colors.base}
label-focused-foreground = ${colors.text}
label-focused-padding = 1

label-occupied = 󰄯
label-occupied-background = ${colors.base}
label-occupied-foreground = ${colors.overlay1}
label-occupied-padding = 1

label-empty = 󰄰
label-empty-background = ${colors.base}
label-empty-foreground = ${colors.text}
label-empty-padding = 1

label-urgent = 
label-urgent-background = ${colors.base}
label-urgent-foreground = ${colors.yellow}
label-urgent-padding = 1

[module/date]
type = internal/date
interval = 1.0
#date = %Y-%m-%d%
date = %A, %d
time = %H:%M

format = <label>
format-background = ${colors.base}
format-foreground = ${colors.text}
format-sufix = " "

#label = " %date% 󰥔 %time% "
label = " %date% | %time% "
label-font = 3
label-foreground = ${colors.text}

[module/now-playing]
type = custom/script

exec = "sh $HOME/.config/polybar/scripts/get_spotify_status.sh"

format = <label>
format-prefix = " "
format-prefix-font = 3
format-prefix-foreground = ${colors.lavender}
format-foreground = ${colors.text}

label = "%output%"
label-maxlen = 30

internal = 1.0

[module/bluetooth]
type = custom/script

exec = "sh $HOME/.config/polybar/scripts/bluetooth.sh"

format = <label>
format-prefix = " 󰂯 "
format-prefix-foreground = ${colors.lavender}
format-prefix-font = 3
format-foreground = ${colors.text}

label = "%output%"

interval = 3.0

[module/wireless-network]
type = internal/network
interface = wlp7s0
interface-type = wireless

interval = 3.0

format-connected-prefix = "󰖩 "
format-connected-prefix-font = 2
format-connected-prefix-foreground = ${colors.lavender}
format-connected = <label-connected>

label-connected = %essid%
label-connected-foreground = ${colors.text}

format-disconnected-prefix = "󰖪 "
format-disconnected-prefix-font = 2
format-disconnected-prefix-foreground = ${colors.overlay1}
format-disconnected = <label-disconnected>

label-disconnected = not connected
label-disconnected-foreground = ${colors.overlay1}

[module/pulseaudio]
type = internal/pulseaudio

interval = 5

format-volume-prefix = " "
format-volume = <label-volume>
format-volume-prefix-font = 2
format-volume-prefix-foreground = ${colors.lavender}
format-volume-suffix = " "

label-volume = %percentage:2%
label-volume-foreground = ${colors.text}

label-muted =  muted
format-muted-prefix-font = 2
format-muted-prefix-foreground = ${colors.overlay1}
label-muted-foreground = ${colors.overlay1}
format-muted-suffix = " "

click-right = pavucontrol

[module/wired-network]
type = internal/network
interface = eth0

[module/cpu]
type = internal/cpu
interval = 3

warn-percentage = 90

format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.sky}
format-prefix-font = 2
format-suffix = " "

label = %percentage:2%%
label-foreground = ${colors.text}
label-warn = %percentage%%
#label-warn-foreground = ${colors.red}



[module/memory]
type = internal/memory
interval = 3

warn-percentage = 80

format = <label>
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.yellow}
format-prefix-font = 2

label = %gb_used:9%
label-foreground = ${colors.text}
label-warn = %gb_used%
#label-warn-foreground = ${colors.red}
